base/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('orders/list/', login_required(views.OrdersList.as_view()), name='orders_list'),
    path('orders/completed/list/', views.OrdersCompletedList.as_view(), name='orders_completed_list'),
    path('order/add/', views.order_add, name='order_add'),
    path('order/edit/<orderId>/', views.order_edit, name='order_edit'),
    path('order/detail/<orderId>/', views.order_detail, name='order_detail'),
    path('order/invoice/<orderId>/', views.order_invoice, name='order_invoice'),
    path('order/change_status/<int:pk>/', views.change_order_status, name='change_order_status'),
    path('tasks/list/', views.TasksList.as_view(), name='tasks_list'),
    path('task/add/', views.task_add, name='task_add'),
    path('task/edit/<taskId>/', views.task_edit, name='task_edit'),
    path('task/detail/<taskId>/', views.task_detail, name='task_detail'),
    path('task/invoice/<taskId>/', views.task_invoice, name='task_invoice'),

    path('department/list/', views.DepartmentList.as_view(), name='department_list'),
    path('department/add/', views.department_add, name='department_add'),
    path('department/edit/<departmentId>/', views.department_edit, name='department_edit'),

    path('operation/list/', views.OperationList.as_view(), name='operation_list'),
    path('operation/add/', views.operation_add, name='operation_add'),
    path('operation/edit/<operationId>/', views.operation_edit, name='operation_edit'),

    path('subgroup/list/', views.SubgroupList.as_view(), name='subgroup_list'),
    path('subgroup/add/', views.subgroup_add, name='subgroup_add'),
    path('subgroup/edit/<subgroupId>/', views.subgroup_edit, name='subgroup_edit'),

    path('ajax/', include('base.ajax_urls')),

    path('persons_report/', views.WorkReportView.as_view(), name='persons_report'),
    path('machines_report/', views.MachineReportView.as_view(), name='machines_report'),

    path("archive-task/<int:pk>/", views.change_task_publish_status, name='archive-task'),
    path("archive-part/<int:pk>/", views.change_part_publish_status, name='archive-part'),
    path("archive-stuff/<int:pk>/", views.change_stuff_publish_status, name='archive-stuff'),
    path("archive-station/<int:pk>/", views.change_station_publish_status, name='archive-station'),
    path("archive-order/<int:pk>/", views.change_order_publish_status, name='archive-order'),
    path("archive-operation/<int:pk>/", views.change_operation_publish_status, name='archive-operation'),

    path('parts/', views.PartsList.as_view(), name='machine_parts_list'),
    path('part/edit/<int:part_id>/', views.PartsList.as_view(), name='machine_part_edit'),
    path('part/add/', views.machine_part_add, name='machine_part_add'),

    # path('stuff/edit/<int:stuff_id>/', views.StuffEdit.as_view(), name='department_stuff_edit'),

    path('stuff/', views.StuffList.as_view(), name='stuff_list'),
    path('stuff/add/', views.machine_stuff_add, name='stuff_add'),

    path('stations/', views.StationList.as_view(), name='station_list'),
    path('station/edit/<int:pk>/', views.StationList.as_view(), name='station_edit'),
    path('station/add/', views.station_add, name='station_add'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('adminbia2/', admin.site.urls),
    path('', include('base.urls')),
    path('users/', include('users.urls')),
    path('review/', include('review.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.utils import timezone
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from base.managers import PublishedManager

User = get_user_model()


class Order(models.Model):
    StatusChoices = (
        ('SV', 'ثبت شده'),
        ('SE', 'مشاهده شده'),
        ("DG", 'در حال انجام'),
        ("WG", "در انتظار قطعه"),
        ('ST', "ارسال به پیمانکار"),
        ("DN", "تکمیل شده")
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    operation = models.ForeignKey('Operation', on_delete=models.SET_NULL, null=True, related_name='order')
    operationName = models.CharField(max_length=300, blank=True, null=True)
    department = models.ForeignKey('Department', on_delete=models.SET_NULL, null=True)
    departmentName = models.CharField(max_length=300, blank=True, null=True)
    subGroup = models.ManyToManyField('Subgroup')
    createdAt = models.DateTimeField(auto_now_add=True)
    description = RichTextField(blank=True, null=True)
    orderId = models.CharField(max_length=50)
    publish = models.BooleanField(default=True)
    is_for_machine = models.BooleanField(default=False)
    is_for_department = models.BooleanField(default=False)
    isConfirmed = models.BooleanField(default=False)  # Confirmed by manager
    priority = models.CharField(max_length=5, blank=True, null=True)
    status = models.CharField(max_length=2, choices=StatusChoices, default='SV')  # Which step is right now
    part = models.ForeignKey('Part', on_delete=models.SET_NULL, null=True, related_name='order')
    stuff = models.ForeignKey('Stuff', on_delete=models.SET_NULL, null=True, related_name='order_stuff')

    # second_status = models.CharField(max_length=2, blank=True, null=True, choices=StatusChoices, default='SV')
    # isCompleted = models.BooleanField(default=False)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        unique_together = ("operation", "description")

    def __str__(self):
        return str(self.orderId)

    @property
    def get_priority(self):
        if self.priority == '1':
            return 'کم'
        elif self.priority == '2':
            return 'متوسط'
        elif self.priority == '3':
            return 'زیاد'


class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Operation(models.Model):
    name = models.CharField(max_length=50)
    area = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, related_name='department_operations')
    station = models.ForeignKey('Station', on_delete=models.SET_NULL, null=True, related_name='station_operations')
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name


class Subgroup(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Task(models.Model):
    TaskChoices = (
        ('SV', 'ثبت شده'),
        ('SE', 'مشاهده شده'),
        ("DG", 'در حال انجام'),
        ("WG", "در انتظار قطعه"),
        ('ST', "ارسال به پیمانکار"),
        ("DN", "تکمیل شده")
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='task')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = RichTextUploadingField()
    description2 = RichTextUploadingField()
    date = models.DateField(null=True)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    publish = models.BooleanField(default=True)
    hours = models.CharField(max_length=20, blank=True, null=True)
    # completed = models.BooleanField(default=False)
    parts = models.ManyToManyField('Part', related_name='task_parts')
    operators = models.ManyToManyField(User, null=True, related_name='operator_tasks')
    status = models.CharField(max_length=2, blank=True, null=True, choices=TaskChoices, default='SV')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ("date",)

    def __str__(self):
        return f'{self.order.orderId}'

    @property
    def get_time_diff(self):
        from datetime import datetime, date
        try:
            time_diff = datetime.combine(date.today(), self.end_time) - datetime.combine(date.today(), self.start_time)
            return time_diff.total_seconds()
        except TypeError as e:
            return 0


class Piece(models.Model):
    part = models.ForeignKey('Part', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='pieces')
    count = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return f'piece for {self.part.name}| count: {self.count}'


class Part(models.Model):
    name = models.CharField(max_length=200)
    machine = models.ForeignKey(Operation, on_delete=models.CASCADE, related_name='parts')

    def __str__(self):
        return self.name


class Stuff(models.Model):
    name = models.CharField(max_length=200)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='stuffs')

    def __str__(self):
        return self.name


class Station(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

templates/part/list.html
{% extends '../base.html' %}

{% load static %}

{% block content %}

<h4 class="py-3 breadcrumb-wrapper mb-2">لیست قطعات</h4>

{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger">{{ message }}</div>
{% else %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endif %}
{% endfor %}

<!-- Role cards -->
<div class="row g-4">
    {% for part in parts %}
    <div class="col-xl-4 col-lg-6 col-md-6">
        <div class="card">
            <div class="card-body">
                <div class="d-flex justify-content-between mb-1">
                    <h6 class="fw-normal">{{ part.order_set.all|length }}</h6>

                </div>
                <div class="d-flex justify-content-between align-items-end">
                    <div class="role-heading">
                        <h4 class="mb-1">{{ part.name }}</h4>
                        <a href="javascript:;" data-bs-toggle="modal" data-bs-target="#editpartModal_{{ part.id }}"
                            class="role-edit-modal"><small>ویرایش
                                قطعه</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ Edit Role Modal -->
    <div class="modal fade" id="editpartModal_{{ part.id }}" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-lg modal-dialog-centered modal-add-new-role">
            <div class="modal-content p-3 p-md-5">
                <button type="button" class="btn-close btn-pinned" data-bs-dismiss="modal" aria-label="Close"></button>
                <div class="modal-body">
                    <div class="text-center mb-4">
                        <h3>ویرایش قطعه</h3>
                    </div>
                    <!-- Edit role form -->
                    <form method="post" class="row g-3" action="{% url 'part_edit' part.id %}">
                        {% csrf_token %}
                        <div class="col-12 mb-2">
                            <label class="form-label" for="partName">نام قطعه</label>
                            <input type="text" id="partName" name="partName" class="form-control"
                                value="{{ part.name }}" tabindex="-1" required>
                        </div>
                        <div class="col-12 mb-4">
                            <label class="form-label" for="partDesc">توضیحات قطعه</label>
                            <textarea id="partDesc" name="partDesc" class="form-control" rows="2"
                                placeholder="توضیحات قطعه را وارد کنید" tabindex="-1">{{ part.description }}</textarea>
                        </div>

                        <div class="col-12 text-center">
                            <button type="submit" class="btn btn-primary me-sm-3 me-1">ویرایش</button>
                            <button type="reset" class="btn btn-label-secondary" data-bs-dismiss="modal"
                                aria-label="Close">
                                انصراف
                            </button>
                        </div>
                    </form>
                    <!--/ Edit role form -->
                </div>
            </div>
        </div>
    </div>
    <!-- / Edit Role Modal -->
    {% endfor %}
    <div class="col-xl-4 col-lg-6 col-md-6">
        <div class="card h-100">
            <div class="row h-100">
                <div class="col-sm-5">
                    <div class="d-flex align-items-end h-100 justify-content-center mt-sm-0 mt-3">
                        <img src="{% static 'img/illustrations/lady-with-laptop-light.png' %}" class="img-fluid"
                            alt="Image" width="100" data-app-light-img="illustrations/lady-with-laptop-light.png"
                            data-app-dark-img="illustrations/lady-with-laptop-dark.png">
                    </div>
                </div>
                <div class="col-sm-7">
                    <div class="card-body text-sm-end text-center ps-sm-0">
                        <button data-bs-target="#addpartModal" data-bs-toggle="modal"
                            class="btn btn-primary mb-3 text-nowrap add-new-role">
                            افزودن قطعه جدید
                        </button>
                        <p class="mb-0">اگر قطعهی وجود ندارد اضافه کنید</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ Role cards -->

<!--/ Add Role Modal -->
<div class="modal fade" id="addpartModal" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-add-new-role">
        <div class="modal-content p-3 p-md-5">
            <button type="button" class="btn-close btn-pinned" data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-body">
                <div class="text-center mb-4">
                    <h3>افزودن قطعه جدید</h3>
                    <p>مجوزهای قطعه را تنظیم کنید</p>
                </div>
                <!-- Add role form -->
                <form method="post" class="row g-3" action="{% url 'part_add' %}">
                    {% csrf_token %}
                    <div class="col-12 mb-2">
                        <label class="form-label" for="partName">نام قطعه</label>
                        <input type="text" id="partName" name="partName" class="form-control"
                            placeholder="نام قطعه را وارد کنید" tabindex="-1" required>
                    </div>
                    <div class="col-12 mb-4">
                        <label class="form-label" for="partDesc">توضیحات قطعه</label>
                        <textarea id="partDesc" name="partDesc" class="form-control" rows="2"
                            placeholder="توضیحات قطعه را وارد کنید" tabindex="-1"></textarea>
                    </div>
                    <div class="col-12 text-center">
                        <button type="submit" class="btn btn-primary me-sm-3 me-1">ثبت</button>
                        <button type="reset" class="btn btn-label-secondary" data-bs-dismiss="modal" aria-label="Close">
                            انصراف
                        </button>
                    </div>
                </form>
                <!--/ Add role form -->
            </div>
        </div>
    </div>
</div>
<!-- / Add Role Modal -->
{% endblock content %}