base/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('orders/list/', login_required(views.OrdersList.as_view()), name='orders_list'),
    path('orders/completed/list/', views.OrdersCompletedList.as_view(), name='orders_completed_list'),
    path('order/add/', views.order_add, name='order_add'),
    path('order/edit/<orderId>/', views.order_edit, name='order_edit'),
    path('order/detail/<orderId>/', views.order_detail, name='order_detail'),
    path('order/invoice/<orderId>/', views.order_invoice, name='order_invoice'),
    path('order/change_status/<int:pk>/', views.change_order_status, name='change_order_status'),
    path('tasks/list/', views.TasksList.as_view(), name='tasks_list'),
    path('task/add/', views.task_add, name='task_add'),
    path('task/edit/<taskId>/', views.task_edit, name='task_edit'),
    path('task/detail/<taskId>/', views.task_detail, name='task_detail'),
    path('task/invoice/<taskId>/', views.task_invoice, name='task_invoice'),

    path('department/list/', views.DepartmentList.as_view(), name='department_list'),
    path('department/add/', views.department_add, name='department_add'),
    path('department/edit/<departmentId>/', views.department_edit, name='department_edit'),

    path('operation/list/', views.OperationList.as_view(), name='operation_list'),
    path('operation/add/', views.operation_add, name='operation_add'),
    path('operation/edit/<operationId>/', views.operation_edit, name='operation_edit'),

    path('subgroup/list/', views.SubgroupList.as_view(), name='subgroup_list'),
    path('subgroup/add/', views.subgroup_add, name='subgroup_add'),
    path('subgroup/edit/<subgroupId>/', views.subgroup_edit, name='subgroup_edit'),

    path('ajax/', include('base.ajax_urls')),

    path('persons_report/', views.WorkReportView.as_view(), name='persons_report'),
    path('machines_report/', views.MachineReportView.as_view(), name='machines_report'),

    path("archive-task/<int:pk>/", views.change_task_publish_status, name='archive-task'),
    path("archive-part/<int:pk>/", views.change_part_publish_status, name='archive-part'),
    path("archive-stuff/<int:pk>/", views.change_stuff_publish_status, name='archive-stuff'),
    path("archive-station/<int:pk>/", views.change_station_publish_status, name='archive-station'),
    path("archive-order/<int:pk>/", views.change_order_publish_status, name='archive-order'),
    path("archive-operation/<int:pk>/", views.change_operation_publish_status, name='archive-operation'),

    path('parts/', views.PartsList.as_view(), name='machine_parts_list'),
    path('part/edit/<int:part_id>/', views.PartsList.as_view(), name='machine_part_edit'),
    path('part/add/', views.machine_part_add, name='machine_part_add'),

    # path('stuff/edit/<int:stuff_id>/', views.StuffEdit.as_view(), name='department_stuff_edit'),

    path('stuff/', views.StuffList.as_view(), name='stuff_list'),
    path('stuff/add/', views.machine_stuff_add, name='stuff_add'),

    path('stations/', views.StationList.as_view(), name='station_list'),
    path('station/edit/<int:pk>/', views.StationList.as_view(), name='station_edit'),
    path('station/add/', views.station_add, name='station_add'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('adminbia2/', admin.site.urls),
    path('', include('base.urls')),
    path('users/', include('users.urls')),
    path('review/', include('review.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

review/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list/', views.ReviewList.as_view(), name='review_list'),
    path('add/', views.review_add, name='review_add'),
    path('edit/<reviewId>/', views.review_edit, name='review_edit'),
    path('detail/<reviewId>/', views.review_detail, name='review_detail'),

    path('machine/list/', views.MachineList.as_view(), name='machine_list'),
    path('machine/add/', views.machine_add, name='machine_add'),
    path('machine/edit/<machineId>/', views.machine_edit, name='machine_edit'),

    path('part/list/', views.PartList.as_view(), name='part_list'),
    path('part/add/', views.part_add, name='part_add'),
    path('part/edit/<partId>/', views.part_edit, name='part_edit'),

    path('task/add/<reviewId>/', views.reviewtask_add, name='reviewtask_add'),
    path('task/edit/', views.reviewtask_edit, name='reviewtask_edit'),
]

review/models.py
import datetime
import time
from django.db import models
from django.contrib.auth.models import User


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    part = models.ForeignKey('Part', on_delete=models.SET_NULL, null=True)
    partName = models.CharField(max_length=300)
    machine = models.ForeignKey('Machine', on_delete=models.SET_NULL, null=True)
    machineName = models.CharField(max_length=300)
    reviewPeriod = models.CharField(max_length=200)
    last_sms = models.CharField(default=time.time(), max_length=100)
    # last_sms.editable = True
    reviewCount = models.IntegerField()
    createdAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'بازدید {self.partName} {self.machineName}'

    @property
    def get_reviewPeriod(self):
        if self.reviewPeriod == 'day':
            return 'روز'
        elif self.reviewPeriod == 'month':
            return 'ماه'
        elif self.reviewPeriod == 'year':
            return 'سال'


class Part(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)
    isActive = models.BooleanField(default=True)
    createdAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'


class Machine(models.Model):
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)
    isActive = models.BooleanField(default=True)
    createdAt = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}'


class ReviewTask(models.Model):
    review = models.ForeignKey(Review, on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    done = models.BooleanField(default=False)
    createdAt = models.DateTimeField(auto_now_add=True)

review/forms.py
from django import forms

from .models import Review

PERIOD = (
    ('day', 'روز'),
    ('month', 'ماه'),
    ('year', 'سال'),
)


class ReviewForm(forms.ModelForm):
    reviewPeriod = forms.ChoiceField(choices=PERIOD, label='دوره بازدید')

    class Meta:
        model = Review
        fields = ['part', 'machine', 'reviewPeriod', 'reviewCount']
        labels = {'part': 'نام قطعه', 'machine': 'نام دستگاه', 'reviewCount': 'زمان بازدید'}

    def __init__(self, *args, **kwargs):
        super(ReviewForm, self).__init__(*args, **kwargs)
        self.fields['part'].widget.attrs['class'] = 'select2 form-select form-select-lg'
        self.fields['machine'].widget.attrs['class'] = 'select2 form-select form-select-lg'

review/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages

from .models import *
from .forms import *

import json


class ReviewList(ListView):
    model = Review
    template_name = 'review/list.html'
    context_object_name = 'reviews'
    paginate_by = 10

    def get_queryset(self):
        reviews = Review.objects.all().order_by('-createdAt')

        q = self.request.GET.get('q')
        machine = self.request.GET.get('department')
        part = self.request.GET.get('operation')

        if q:
            reviews = reviews.filter(
                Q(user__username__contains=q) | Q(user__first_name__contains=q) | Q(user__last_name__contains=q))

        if machine:
            reviews = reviews.filter(machine_id=machine)

        if part:
            reviews = reviews.filter(part_id=part)

        return reviews

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['machines'] = Machine.objects.all()
        context['parts'] = Part.objects.all()
        return context


def review_add(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            part = form.cleaned_data['part']
            machine = form.cleaned_data['machine']
            instance = form.save(commit=False)
            instance.user = request.user
            instance.partName = part.name
            instance.machineName = machine.name
            instance.save()

            messages.success(request, 'درخواست بازدید ثبت شد')
            return redirect('review_list')
    else:
        form = ReviewForm()

    context = {'form': form}
    return render(request, 'review/add.html', context)


def review_edit(request, reviewId):
    review = Review.objects.get(id=reviewId)
    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            part = form.cleaned_data['part']
            machine = form.cleaned_data['machine']
            instance = form.save(commit=False)
            instance.partName = part.name
            instance.machineName = machine.name
            instance.save()

            messages.success(request, 'درخواست بازدید ویرایش شد')
            return redirect('review_list')
    else:
        form = ReviewForm(request.POST or None, instance=review)

    context = {'form': form, 'review': review}
    return render(request, 'review/edit.html', context)


def review_detail(request, reviewId):
    review = Review.objects.get(id=reviewId)

    context = {'review': review}
    return render(request, 'review/detail.html', context)


class MachineList(ListView):
    model = Machine
    template_name = 'machine/list.html'
    paginate_by = 100
    context_object_name = 'machines'


def machine_add(request):
    if request.method == 'POST':
        name = request.POST.get('machineName')
        Machine.objects.get_or_create(name=name)
        messages.success(request, 'واحد ایجاد شد')
        return redirect('machine_list')


def machine_edit(request, machineId):
    if request.method == 'POST':
        name = request.POST.get('machineName')
        Machine.objects.filter(id=machineId).update(name=name)
        messages.success(request, 'واحد ویرایش شد')
        return redirect('machine_list')


class PartList(ListView):
    model = Part
    template_name = 'part/list.html'
    paginate_by = 100
    context_object_name = 'parts'


def part_add(request):
    if request.method == 'POST':
        name = request.POST.get('partName')
        description = request.POST.get('partDesc')
        part, created = Part.objects.get_or_create(name=name)
        part.description = description
        part.save()
        messages.success(request, 'قطعه ایجاد شد')
        return redirect('part_list')


def part_edit(request, partId):
    if request.method == 'POST':
        name = request.POST.get('partName')
        description = request.POST.get('partDesc')
        Part.objects.filter(id=partId).update(name=name, description=description)
        messages.success(request, 'قطعه ویرایش شد')
        return redirect('part_list')


def reviewtask_add(request, reviewId):
    review = Review.objects.get(id=reviewId)
    if request.method == 'POST':
        description = request.POST.get('description')
        done = request.POST.get('done')

        ReviewTask.objects.create(review=review, description=description, done=done)
        messages.success(request, 'بازدید ثبت شد')
        return redirect('review_list')


def reviewtask_edit(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        description = data['description']
        done = data['done']
        taskId = data['taskId']

        print('taskId', taskId)

        ReviewTask.objects.filter(id=taskId).update(description=description, done=done)
        messages = {'status': 200, 'text': 'بازدید ویرایش شد'}
        return JsonResponse(messages, safe=False)

templates/review/add.html
{% extends '../base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<h4 class="py-3 breadcrumb-wrapper mb-2">ثبت درخواست بازدید دوره ای</h4>

{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger">{{ message }}</div>
{% else %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endif %}
{% endfor %}

<div class="card">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="row g-4">
                <div class="col-md-3 mb-2">{{ form.machine|as_crispy_field }}</div>
                <div class="col-md-3 mb-2">{{ form.part|as_crispy_field }}</div>
                <div class="col-md-3 mb-2">{{ form.reviewPeriod|as_crispy_field }}</div>
                <div class="col-md-3 mb-2">{{ form.reviewCount|as_crispy_field }}</div>
            </div>
            <div class="mt-1">
                <button type="submit" class="btn btn-primary me-2">ثبت</button>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

templates/review/detail.html
{% extends '../base.html' %}

{% load static %}
{% load jalali_tags %}
{% load crispy_forms_tags %}

{% block content %}

<h4 class="py-3 breadcrumb-wrapper mb-2">مشاهده بازدیدها</h4>

{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger">{{ message }}</div>
{% else %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endif %}
{% endfor %}

<div class="card">
    <div class="card-body">
        <!-- View Review Details -->
        <div class="row g-3">
            <div class="d-flex" style="justify-content: space-between;">
                <h4>جزئیات درخواست بازدید</h4>
                <button href="#" data-bs-target="#reviewTaskAdd" data-bs-toggle="modal"
                    class="btn btn-label-primary">ثبت
                    بازدید جدید</button>
            </div>

            <div class="table-responsive">
                <table class="table table-bordered">
                    <tr>
                        <td colspan="2">درخواست کننده : <b>{{ review.user.profile }}</b></td>
                        <td colspan="2">تاریخ درخواست : <b>{{ review.createdAt|to_jalali:"%y/%m/%d" }}</b></td>
                    </tr>
                    <tr>
                        <td>دستگاه : <b>{{ review.machineName }}</b></td>
                        <td>قطعه : <b>{{ review.partName }}</b></td>
                        <td>دوره بازدید : <b>{{ review.reviewCount }} {{ review.get_reviewPeriod }}</b></td>
                    </tr>
                </table>
            </div>

            {% if review.reviewtask_set.all %}
            <div class="table-responsive">
                <h4>لیست بازدید های انجام شده</h4>
                <table class="table table-bordered text-center">
                    <thead>
                        <tr>
                            <th>تاریخ</th>
                            <th>شرح فعالیت</th>
                            <th>وضعیت</th>
                            <th>عملیات</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for task in review.reviewtask_set.all %}
                        <tr>
                            <td>{{ task.createdAt|to_jalali:'%y/%m/%d' }}</td>
                            <td>
                                <input type="text" class="form-control" name="description"
                                    id="description_{{ task.id }}" value="{{ task.description }}" disabled>
                            </td>
                            <td>
                                <select name="done" id="done_{{ task.id }}" class="form-select" disabled>
                                    <option value="1" {% if task.done %} selected {% endif %}>انجام شده</option>
                                    <option value="0" {% if not task.done %} selected {% endif %}>انجام نشده</option>
                                </select>
                            </td>
                            <td>
                                <button data-id="{{ task.id }}" data-function="edit"
                                    class="btn btn-sm btn-icon reviewTaskEditBtn">
                                    <i class="bx bx-edit"></i>
                                </button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            {% else %}
            <div class="alert alert-warning">بازدیدی انجام نشده است</div>
            {% endif %}
        </div>
        <!--/ View Review Details -->
    </div>
</div>

<div class="modal fade" id="reviewTaskAdd" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered modal-add-new-role">
        <div class="modal-content p-3 p-md-5">
            <button type="button" class="btn-close btn-pinned" data-bs-dismiss="modal" aria-label="Close"></button>
            <div class="modal-body">
                <h4>افزودن بازدید جدید</h4>
                <form action="{% url 'reviewtask_add' review.id %}" method="post">
                    {% csrf_token %}

                    <div class="col-md-4">
                        <label for="" class="form-label">وضعیت</label>
                        <select class="form-select" name="done" id="">
                            <option value="1">انجام شد</option>
                            <option value="0">انجام نشد</option>
                        </select>
                    </div>
                    <div class="col-md-12 mb-2">
                        <label class="form-label">توضیحات</label>
                        <textarea class="form-control" name="description" id="" cols="30" rows="3"></textarea>
                    </div>

                    <div class="col-md-12" style="text-align: left;">
                        <button type="submit" class="btn btn-label-primary">ثبت</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/review/edit.html
{% extends '../base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<h4 class="py-3 breadcrumb-wrapper mb-2">ویرایش درخواست بازدید دوره ای</h4>

{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger">{{ message }}</div>
{% else %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endif %}
{% endfor %}

<div class="card">
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            <div class="row g-4">
                <div class="col-md-3 mb-2">{{ form.machine|as_crispy_field }}</div>
                <div class="col-md-3 mb-2">{{ form.part|as_crispy_field }}</div>
                <div class="col-md-3 mb-2">{{ form.reviewPeriod|as_crispy_field }}</div>
                <div class="col-md-3 mb-2">{{ form.reviewCount|as_crispy_field }}</div>
            </div>
            <div class="mt-1">
                <button type="submit" class="btn btn-primary me-2">ویرایش</button>
            </div>
        </form>
    </div>
</div>


{% endblock content %}

templates/review/list.html
{% extends '../base.html' %}

{% load static %}
{% load jalali_tags %}

{% block content %}

<h4 class="py-3 breadcrumb-wrapper mb-2">لیست بازدید ها</h4>

{% for message in messages %}
{% if message.tags == 'error' %}
<div class="alert alert-danger">{{ message }}</div>
{% else %}
<div class="alert alert-{{ message.tags }}">{{ message }}</div>
{% endif %}
{% endfor %}

<div class="card">
    <div class="card-header border-bottom">
        <h5 class="card-title">فیلتر جستجو</h5>
        <form action="{% url 'review_list' %}">
            <div class="d-flex justify-content-between align-items-center row py-3 gap-3 gap-md-0">
                <div class="col-md-3 user_role">
                    <input class="form-control" type="search" name="q" value="{{ request.GET.q }}"
                        placeholder="جستجو براساس نام درخواست کننده">
                </div>
                <div class="col-md-3 user_plan">
                    <select class="form-select" name="machine" id="">
                        <option value="">انتخاب دستگاه</option>
                        {% for machine in machines %}
                        <option value="{{ machine.id }}" {% if request.GET.machine|add:0 == machine.id %} selected
                            {% endif %}>{{ machine.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-3 order_status">
                    <select class="form-select" name="part" id="">
                        <option value="">انتخاب قطعه</option>
                        {% for part in parts %}
                        <option value="{{ part.id }}" {% if request.GET.part|add:0 == part.id %} selected {% endif %}>
                        </option>
                        {{ part.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-3 user_status">
                    <button type="submit" class="btn btn-label-primary">اعمال فیلتر</button>
                </div>
            </div>
        </form>
    </div>
    <div class="card-datatable table-responsive">
        <table class="table border-top text-center">
            <thead>
                <tr>
                    <th>#</th>
                    <th>نام درخواست دهنده</th>
                    <th>دستگاه</th>
                    <th>قطعه</th>
                    <th>تاریخ ایجاد</th>
                    <th>عمل‌ها</th>
                </tr>
            </thead>
            <tbody>
                {% for review in reviews %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ review.user.profile }}</td>
                    <td><span class="badge bg-label-primary">{{ review.machineName }}</span></td>
                    <td><span class="badge bg-label-success">{{ review.partName }}</span></td>
                    <td>{{ review.createdAt|to_jalali:'%y/%m/%d' }}</td>
                    </td>
                    <td>
                        <div class="d-inline-block text-nowrap">
                            {% if perms.base.change_review %}
                            <a href="{% url 'review_edit' review.id %}" class="btn btn-sm btn-icon">
                                <i class="bx bx-edit"></i>
                            </a>
                            {% endif %}
                            <a href="{% url 'review_detail' review.id %}" class="btn btn-sm btn-icon delete-record">
                                <i class="bx bx-show"></i>
                            </a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}