base/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('orders/list/', login_required(views.OrdersList.as_view()), name='orders_list'),
    path('orders/completed/list/', views.OrdersCompletedList.as_view(), name='orders_completed_list'),
    path('order/add/', views.order_add, name='order_add'),
    path('order/edit/<orderId>/', views.order_edit, name='order_edit'),
    path('order/detail/<orderId>/', views.order_detail, name='order_detail'),
    path('order/invoice/<orderId>/', views.order_invoice, name='order_invoice'),
    path('order/change_status/<int:pk>/', views.change_order_status, name='change_order_status'),
    path('tasks/list/', views.TasksList.as_view(), name='tasks_list'),
    path('task/add/', views.task_add, name='task_add'),
    path('task/edit/<taskId>/', views.task_edit, name='task_edit'),
    path('task/detail/<taskId>/', views.task_detail, name='task_detail'),
    path('task/invoice/<taskId>/', views.task_invoice, name='task_invoice'),

    path('department/list/', views.DepartmentList.as_view(), name='department_list'),
    path('department/add/', views.department_add, name='department_add'),
    path('department/edit/<departmentId>/', views.department_edit, name='department_edit'),

    path('operation/list/', views.OperationList.as_view(), name='operation_list'),
    path('operation/add/', views.operation_add, name='operation_add'),
    path('operation/edit/<operationId>/', views.operation_edit, name='operation_edit'),

    path('subgroup/list/', views.SubgroupList.as_view(), name='subgroup_list'),
    path('subgroup/add/', views.subgroup_add, name='subgroup_add'),
    path('subgroup/edit/<subgroupId>/', views.subgroup_edit, name='subgroup_edit'),

    path('ajax/', include('base.ajax_urls')),

    path('persons_report/', views.WorkReportView.as_view(), name='persons_report'),
    path('machines_report/', views.MachineReportView.as_view(), name='machines_report'),

    path("archive-task/<int:pk>/", views.change_task_publish_status, name='archive-task'),
    path("archive-part/<int:pk>/", views.change_part_publish_status, name='archive-part'),
    path("archive-stuff/<int:pk>/", views.change_stuff_publish_status, name='archive-stuff'),
    path("archive-station/<int:pk>/", views.change_station_publish_status, name='archive-station'),
    path("archive-order/<int:pk>/", views.change_order_publish_status, name='archive-order'),
    path("archive-operation/<int:pk>/", views.change_operation_publish_status, name='archive-operation'),

    path('parts/', views.PartsList.as_view(), name='machine_parts_list'),
    path('part/edit/<int:part_id>/', views.PartsList.as_view(), name='machine_part_edit'),
    path('part/add/', views.machine_part_add, name='machine_part_add'),

    # path('stuff/edit/<int:stuff_id>/', views.StuffEdit.as_view(), name='department_stuff_edit'),

    path('stuff/', views.StuffList.as_view(), name='stuff_list'),
    path('stuff/add/', views.machine_stuff_add, name='stuff_add'),

    path('stations/', views.StationList.as_view(), name='station_list'),
    path('station/edit/<int:pk>/', views.StationList.as_view(), name='station_edit'),
    path('station/add/', views.station_add, name='station_add'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('adminbia2/', admin.site.urls),
    path('', include('base.urls')),
    path('users/', include('users.urls')),
    path('review/', include('review.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.utils import timezone
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from base.managers import PublishedManager

User = get_user_model()


class Order(models.Model):
    StatusChoices = (
        ('SV', 'ثبت شده'),
        ('SE', 'مشاهده شده'),
        ("DG", 'در حال انجام'),
        ("WG", "در انتظار قطعه"),
        ('ST', "ارسال به پیمانکار"),
        ("DN", "تکمیل شده")
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    operation = models.ForeignKey('Operation', on_delete=models.SET_NULL, null=True, related_name='order')
    operationName = models.CharField(max_length=300, blank=True, null=True)
    department = models.ForeignKey('Department', on_delete=models.SET_NULL, null=True)
    departmentName = models.CharField(max_length=300, blank=True, null=True)
    subGroup = models.ManyToManyField('Subgroup')
    createdAt = models.DateTimeField(auto_now_add=True)
    description = RichTextField(blank=True, null=True)
    orderId = models.CharField(max_length=50)
    publish = models.BooleanField(default=True)
    is_for_machine = models.BooleanField(default=False)
    is_for_department = models.BooleanField(default=False)
    isConfirmed = models.BooleanField(default=False)  # Confirmed by manager
    priority = models.CharField(max_length=5, blank=True, null=True)
    status = models.CharField(max_length=2, choices=StatusChoices, default='SV')  # Which step is right now
    part = models.ForeignKey('Part', on_delete=models.SET_NULL, null=True, related_name='order')
    stuff = models.ForeignKey('Stuff', on_delete=models.SET_NULL, null=True, related_name='order_stuff')

    # second_status = models.CharField(max_length=2, blank=True, null=True, choices=StatusChoices, default='SV')
    # isCompleted = models.BooleanField(default=False)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        unique_together = ("operation", "description")

    def __str__(self):
        return str(self.orderId)

    @property
    def get_priority(self):
        if self.priority == '1':
            return 'کم'
        elif self.priority == '2':
            return 'متوسط'
        elif self.priority == '3':
            return 'زیاد'


class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Operation(models.Model):
    name = models.CharField(max_length=50)
    area = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, related_name='department_operations')
    station = models.ForeignKey('Station', on_delete=models.SET_NULL, null=True, related_name='station_operations')
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name


class Subgroup(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Task(models.Model):
    TaskChoices = (
        ('SV', 'ثبت شده'),
        ('SE', 'مشاهده شده'),
        ("DG", 'در حال انجام'),
        ("WG", "در انتظار قطعه"),
        ('ST', "ارسال به پیمانکار"),
        ("DN", "تکمیل شده")
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='task')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = RichTextUploadingField()
    description2 = RichTextUploadingField()
    date = models.DateField(null=True)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    publish = models.BooleanField(default=True)
    hours = models.CharField(max_length=20, blank=True, null=True)
    # completed = models.BooleanField(default=False)
    parts = models.ManyToManyField('Part', related_name='task_parts')
    operators = models.ManyToManyField(User, null=True, related_name='operator_tasks')
    status = models.CharField(max_length=2, blank=True, null=True, choices=TaskChoices, default='SV')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ("date",)

    def __str__(self):
        return f'{self.order.orderId}'

    @property
    def get_time_diff(self):
        from datetime import datetime, date
        try:
            time_diff = datetime.combine(date.today(), self.end_time) - datetime.combine(date.today(), self.start_time)
            return time_diff.total_seconds()
        except TypeError as e:
            return 0


class Piece(models.Model):
    part = models.ForeignKey('Part', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='pieces')
    count = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return f'piece for {self.part.name}| count: {self.count}'


class Part(models.Model):
    name = models.CharField(max_length=200)
    machine = models.ForeignKey(Operation, on_delete=models.CASCADE, related_name='parts')

    def __str__(self):
        return self.name


class Stuff(models.Model):
    name = models.CharField(max_length=200)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='stuffs')

    def __str__(self):
        return self.name


class Station(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

base/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):
    description = forms.TextInput()

    class Meta:
        model = Order
        fields = ['description']
        labels = {'description': 'توضیحات'}

base/templates/base/parts_list.html
{% extends 'base.html' %}

{% load static %}
{% load jalali_tags %}
{% block content %}

    <div class="d-flex justify-content-between mb-2">
        <h4 class="breadcrumb-wrapper mb-0">لیست قطعات ماشین ها</h4>
        <input type="hidden" id="create_for_value" value="{{ create_for }}">

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-success h-25 align-self-center" data-bs-toggle="modal"
                data-bs-target="#modalCenter" id="createNewPart">
            افزودن
        </button>

        <!-- Modal -->
        <div class="modal fade" id="modalCenter" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title secondary-font" id="modalCenterTitle">ساخت قطعه جدید</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'machine_part_add' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col mb-3">
                                    <label for="nameWithTitle" class="form-label">نام</label>
                                    <input type="text" id="nameWithTitle" name="part_name" class="form-control"
                                           placeholder="نام قطعه">
                                </div>
                            </div>
                            <div class="row g-2">
                                <div class="col mb-0">
                                    <label for="emailWithTitle" class="form-label">ماشین</label>
                                    <select name="machine" id="" class="form-control">
                                        {% for machine in machines %}
                                            <option value="{{ machine.id }}"
                                                    {% if create_for == machine.name %}selected{% endif %}>{{ machine.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">ایجاد</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
    {% endfor %}
    {% if part_list %}
        <div class="card">
            <div class="card-datatable table-responsive">
                <table class="table border-top text-center table-striped">
                    <thead class="table-dark">
                    <tr>
                        <th>نام فطعه</th>
                        <th>نام ماشین</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for part in part_list %}
                        <tr>
                            <td>{{ part.name }}</td>
                            <td>{{ part.machine.name }}</td>
                            <td>
                                <div class="d-flex justify-content-center">
                                    {% if perms.base.change_task %}
                                        <a href="{% url 'machine_part_edit' part.id %}" class="btn btn-sm btn-icon">
                                            <i class="bx bx-edit"></i>
                                        </a>
                                    {% endif %}
                                    {% if user.is_superuser %}
                                        <a href="javascript:;" data-bs-toggle="modal"
                                           data-bs-target="#deleteTaskModal_{{ part.id }}"
                                           class="role-edit-modal text-danger btn btn-sm btn-icon">
                                            <i class="bx bx-trash"></i>
                                        </a>
                                        <div class="modal fade" id="deleteTaskModal_{{ part.id }}" tabindex="-1"
                                             aria-hidden="true">
                                            <div class="modal-dialog modal-lg modal-dialog-centered modal-add-new-role">
                                                <div class="modal-content">
                                                    <button type="button" class="btn-close btn-pinned"
                                                            data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                    <div class="modal-body">
                                                        <div class="text-center mb-4">
                                                            <h3 class="role-title">آیا میخواهید قطعه حذف شود؟</h3>
                                                        </div>
                                                        <form method="post" class="row g-3"
                                                              action="{% url 'archive-part' part.id %}">
                                                            {% csrf_token %}
                                                            <div class="col-12 text-center">
                                                                <button type="submit"
                                                                        class="btn btn-danger me-sm-3 me-1">
                                                                    بله
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="pagination justify-content-center">
                    {% if is_paginated %}
                        <div class="card-footer">
                            <div style="text-align: center;">

                                {% if page_obj.has_previous %}
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#" data-num="1">اولین
                                        صفحه</a>
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                       data-num="{{ page_obj.previous_page_number }}">قبلی</a>
                                {% endif %}

                                {% for num in page_obj.paginator.page_range %}
                                    {% if page_obj.number == num %}
                                        <a class="btn btn-primary btn-sm  paging" href="#"
                                           data-num="{{ num }}">{{ num }}</a>
                                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                        <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                           data-num="{{ num }}">{{ num }}</a>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                       data-num="{{ page_obj.next_page_number }}">بعدی</a>
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                       data-num="{{ page_obj.paginator.num_pages }}">
                                        آخرین صفحه</a>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <p>قطعه ای ساخته نشده است</p>
    {% endif %}
    <script>
        window.onload = function () {
            let createFor = document.getElementById('create_for_value')
            if (createFor.value !== 'None') {
                let modalBtn = document.getElementById('createNewPart')
                modalBtn.click()
            }
        }
    </script>
{% endblock content %}

base/templates/base/station_list.html
{% extends 'base.html' %}

{% load static %}
{% load jalali_tags %}
{% block content %}

    <div class="d-flex justify-content-between mb-2">
        <h4 class="breadcrumb-wrapper mb-0">لیست ایستگاه ها</h4>
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-success h-25 align-self-center" data-bs-toggle="modal"
                data-bs-target="#modalCenter">
            افزودن
        </button>

        <!-- Modal -->
        <div class="modal fade" id="modalCenter" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title secondary-font" id="modalCenterTitle">ساخت ایستگاه جدید</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{% url 'station_add' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col mb-3">
                                    <label for="nameWithTitle" class="form-label">نام</label>
                                    <input type="text" id="nameWithTitle" name="station_name" class="form-control"
                                           placeholder="نام ایستگاه">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">ایجاد</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
    {% endfor %}
    {% if station_list %}
        <div class="card">
            <div class="card-datatable table-responsive">
                <table class="table border-top text-center table-striped">
                    <thead class="table-dark">
                    <tr>
                        <th>نام ایستگاه</th>
                        <th>عملیات</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for station in station_list %}
                        <tr>
                            <td>{{ station.name }}</td>
                            <td>
                                <div class="d-flex justify-content-center">
                                    {% if perms.base.change_task %}
                                        <a href="{% url 'station_edit' station.id %}" class="btn btn-sm btn-icon">
                                            <i class="bx bx-edit"></i>
                                        </a>
                                    {% endif %}
                                    {% if user.is_superuser %}
                                        <a href="javascript:;" data-bs-toggle="modal"
                                           data-bs-target="#deleteTaskModal_{{ station.id }}"
                                           class="role-edit-modal text-danger btn btn-sm btn-icon">
                                            <i class="bx bx-trash"></i>
                                        </a>
                                        <div class="modal fade" id="deleteTaskModal_{{ station.id }}" tabindex="-1"
                                             aria-hidden="true">
                                            <div class="modal-dialog modal-lg modal-dialog-centered modal-add-new-role">
                                                <div class="modal-content">
                                                    <button type="button" class="btn-close btn-pinned"
                                                            data-bs-dismiss="modal"
                                                            aria-label="Close"></button>
                                                    <div class="modal-body">
                                                        <div class="text-center mb-4">
                                                            <h3 class="role-title">آیا میخواهید ایستگاه حذف شود؟</h3>
                                                        </div>
                                                        <form method="post" class="row g-3"
                                                              action="{% url 'archive-station' station.id %}">
                                                            {% csrf_token %}
                                                            <div class="col-12 text-center">
                                                                <button type="submit"
                                                                        class="btn btn-danger me-sm-3 me-1">
                                                                    بله
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <div class="pagination justify-content-center">
                    {% if is_paginated %}
                        <div class="card-footer">
                            <div style="text-align: center;">

                                {% if page_obj.has_previous %}
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#" data-num="1">اولین
                                        صفحه</a>
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                       data-num="{{ page_obj.previous_page_number }}">قبلی</a>
                                {% endif %}

                                {% for num in page_obj.paginator.page_range %}
                                    {% if page_obj.number == num %}
                                        <a class="btn btn-primary btn-sm  paging" href="#"
                                           data-num="{{ num }}">{{ num }}</a>
                                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                        <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                           data-num="{{ num }}">{{ num }}</a>
                                    {% endif %}
                                {% endfor %}

                                {% if page_obj.has_next %}
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                       data-num="{{ page_obj.next_page_number }}">بعدی</a>
                                    <a class="btn btn-outline-primary btn-sm  paging" href="#"
                                       data-num="{{ page_obj.paginator.num_pages }}">
                                        آخرین صفحه</a>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <p>ایستگاهی ساخته نشده است</p>
    {% endif %}

{% endblock content %}