base/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    path('', views.index, name='index'),

    path('orders/list/', login_required(views.OrdersList.as_view()), name='orders_list'),
    path('orders/completed/list/', views.OrdersCompletedList.as_view(), name='orders_completed_list'),
    path('order/add/', views.order_add, name='order_add'),
    path('order/edit/<orderId>/', views.order_edit, name='order_edit'),
    path('order/detail/<orderId>/', views.order_detail, name='order_detail'),
    path('order/invoice/<orderId>/', views.order_invoice, name='order_invoice'),
    path('order/change_status/<int:pk>/', views.change_order_status, name='change_order_status'),
    path('tasks/list/', views.TasksList.as_view(), name='tasks_list'),
    path('task/add/', views.task_add, name='task_add'),
    path('task/edit/<taskId>/', views.task_edit, name='task_edit'),
    path('task/detail/<taskId>/', views.task_detail, name='task_detail'),
    path('task/invoice/<taskId>/', views.task_invoice, name='task_invoice'),

    path('department/list/', views.DepartmentList.as_view(), name='department_list'),
    path('department/add/', views.department_add, name='department_add'),
    path('department/edit/<departmentId>/', views.department_edit, name='department_edit'),

    path('operation/list/', views.OperationList.as_view(), name='operation_list'),
    path('operation/add/', views.operation_add, name='operation_add'),
    path('operation/edit/<operationId>/', views.operation_edit, name='operation_edit'),

    path('subgroup/list/', views.SubgroupList.as_view(), name='subgroup_list'),
    path('subgroup/add/', views.subgroup_add, name='subgroup_add'),
    path('subgroup/edit/<subgroupId>/', views.subgroup_edit, name='subgroup_edit'),

    path('ajax/', include('base.ajax_urls')),

    path('persons_report/', views.WorkReportView.as_view(), name='persons_report'),
    path('machines_report/', views.MachineReportView.as_view(), name='machines_report'),

    path("archive-task/<int:pk>/", views.change_task_publish_status, name='archive-task'),
    path("archive-part/<int:pk>/", views.change_part_publish_status, name='archive-part'),
    path("archive-stuff/<int:pk>/", views.change_stuff_publish_status, name='archive-stuff'),
    path("archive-station/<int:pk>/", views.change_station_publish_status, name='archive-station'),
    path("archive-order/<int:pk>/", views.change_order_publish_status, name='archive-order'),
    path("archive-operation/<int:pk>/", views.change_operation_publish_status, name='archive-operation'),

    path('parts/', views.PartsList.as_view(), name='machine_parts_list'),
    path('part/edit/<int:part_id>/', views.PartsList.as_view(), name='machine_part_edit'),
    path('part/add/', views.machine_part_add, name='machine_part_add'),

    # path('stuff/edit/<int:stuff_id>/', views.StuffEdit.as_view(), name='department_stuff_edit'),

    path('stuff/', views.StuffList.as_view(), name='stuff_list'),
    path('stuff/add/', views.machine_stuff_add, name='stuff_add'),

    path('stations/', views.StationList.as_view(), name='station_list'),
    path('station/edit/<int:pk>/', views.StationList.as_view(), name='station_edit'),
    path('station/add/', views.station_add, name='station_add'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('adminbia2/', admin.site.urls),
    path('', include('base.urls')),
    path('users/', include('users.urls')),
    path('review/', include('review.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.utils import timezone
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth import get_user_model
from base.managers import PublishedManager

User = get_user_model()


class Order(models.Model):
    StatusChoices = (
        ('SV', 'ثبت شده'),
        ('SE', 'مشاهده شده'),
        ("DG", 'در حال انجام'),
        ("WG", "در انتظار قطعه"),
        ('ST', "ارسال به پیمانکار"),
        ("DN", "تکمیل شده")
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    operation = models.ForeignKey('Operation', on_delete=models.SET_NULL, null=True, related_name='order')
    operationName = models.CharField(max_length=300, blank=True, null=True)
    department = models.ForeignKey('Department', on_delete=models.SET_NULL, null=True)
    departmentName = models.CharField(max_length=300, blank=True, null=True)
    subGroup = models.ManyToManyField('Subgroup')
    createdAt = models.DateTimeField(auto_now_add=True)
    description = RichTextField(blank=True, null=True)
    orderId = models.CharField(max_length=50)
    publish = models.BooleanField(default=True)
    is_for_machine = models.BooleanField(default=False)
    is_for_department = models.BooleanField(default=False)
    isConfirmed = models.BooleanField(default=False)  # Confirmed by manager
    priority = models.CharField(max_length=5, blank=True, null=True)
    status = models.CharField(max_length=2, choices=StatusChoices, default='SV')  # Which step is right now
    part = models.ForeignKey('Part', on_delete=models.SET_NULL, null=True, related_name='order')
    stuff = models.ForeignKey('Stuff', on_delete=models.SET_NULL, null=True, related_name='order_stuff')

    # second_status = models.CharField(max_length=2, blank=True, null=True, choices=StatusChoices, default='SV')
    # isCompleted = models.BooleanField(default=False)

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        unique_together = ("operation", "description")

    def __str__(self):
        return str(self.orderId)

    @property
    def get_priority(self):
        if self.priority == '1':
            return 'کم'
        elif self.priority == '2':
            return 'متوسط'
        elif self.priority == '3':
            return 'زیاد'


class Department(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Operation(models.Model):
    name = models.CharField(max_length=50)
    area = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, related_name='department_operations')
    station = models.ForeignKey('Station', on_delete=models.SET_NULL, null=True, related_name='station_operations')
    created_at = models.DateTimeField(default=timezone.now)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return self.name


class Subgroup(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Task(models.Model):
    TaskChoices = (
        ('SV', 'ثبت شده'),
        ('SE', 'مشاهده شده'),
        ("DG", 'در حال انجام'),
        ("WG", "در انتظار قطعه"),
        ('ST', "ارسال به پیمانکار"),
        ("DN", "تکمیل شده")
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='task')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = RichTextUploadingField()
    description2 = RichTextUploadingField()
    date = models.DateField(null=True)
    start_time = models.TimeField(null=True)
    end_time = models.TimeField(null=True)
    publish = models.BooleanField(default=True)
    hours = models.CharField(max_length=20, blank=True, null=True)
    # completed = models.BooleanField(default=False)
    parts = models.ManyToManyField('Part', related_name='task_parts')
    operators = models.ManyToManyField(User, null=True, related_name='operator_tasks')
    status = models.CharField(max_length=2, blank=True, null=True, choices=TaskChoices, default='SV')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ("date",)

    def __str__(self):
        return f'{self.order.orderId}'

    @property
    def get_time_diff(self):
        from datetime import datetime, date
        try:
            time_diff = datetime.combine(date.today(), self.end_time) - datetime.combine(date.today(), self.start_time)
            return time_diff.total_seconds()
        except TypeError as e:
            return 0


class Piece(models.Model):
    part = models.ForeignKey('Part', on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='pieces')
    count = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return f'piece for {self.part.name}| count: {self.count}'


class Part(models.Model):
    name = models.CharField(max_length=200)
    machine = models.ForeignKey(Operation, on_delete=models.CASCADE, related_name='parts')

    def __str__(self):
        return self.name


class Stuff(models.Model):
    name = models.CharField(max_length=200)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='stuffs')

    def __str__(self):
        return self.name


class Station(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

templates/order/add.html
{% extends '../base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <h4 class="py-3 breadcrumb-wrapper mb-2">ثبت درخواست</h4>

    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
    {% endfor %}

    <div class="card">
        <div class="card-body">
            <form id="formValidationExamples" action="{% url 'order_add' %}" method="post">
                {% csrf_token %}
                <div class="row ">
                    <div class="col-md-3 align-self-center">
                        <div class="mb-1 justify-content-around d-flex">
                            <label for="is_machine">ثبت درخواست ماشین</label>
                            <input type="checkbox" id="is_machine" onchange="changePartDisplay('m')"
                                   name="create_machine">
                        </div>
                        <div class=" justify-content-around d-flex">
                            <label for="is_department">ثبت درخواست محیط</label>
                            <input type="checkbox" id="is_department" onchange="changePartDisplay('d')"
                                   name="create_department">
                        </div>
                    </div>
                    <div class="col-md-3 mb-1" id="operation_div">
                        <label for="" class="form-label">عملیات درخواستی*</label>
                        <select class="select2 form-select form-select-lg" id="operationselect" data-allow-clear="true"
                                onchange="getParts()" name="operation">
                            <option value="">لطفا انتخاب کنید</option>
                            {% for operation in operations %}
                                <option value="{{ operation.id }}">{{ operation.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3 mb-1 d-none" id="department_div">
                        <label for="" class="form-label">محیط درخواستی*</label>
                        <select class="select2 form-select form-select-lg" id="departmentselect" data-allow-clear="true"
                                onchange="getStuff()" name="department">
                            <option value="">لطفا انتخاب کنید</option>
                            {% for department in departments %}
                                <option value="{{ department.id }}">{{ department.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-3 mb-1 d-none" id="part_div">
                        <label for="" class="form-label">قطعات مربوطه</label>
                        <select class="select2 form-select form-select-lg" id="partselect" data-allow-clear="true"
                                name="part">
                            <option value="">لطفا انتخاب کنید</option>
                        </select>
                    </div>
                    <div class="col-md-3 mb-1 d-none" id="stuff_div">
                        <label for="" class="form-label">وسایل مربوطه</label>
                        <select class="select2 form-select form-select-lg" id="stuffselect" data-allow-clear="true"
                                name="stuff">
                            <option value="">لطفا انتخاب کنید</option>
                        </select>
                    </div>
                    <div class="col-md-3 mb-1">
                        <label for="select2Success" class="form-label">زیرگروه</label>
                        <div class="select2-success">
                            <select id="select2Success" class="select2 form-select" name="subgroup" multiple required>
                                {% for subgroup in subgroups %}
                                    <option value="{{ subgroup.id }}">{{ subgroup.name }} </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3 mb-1">
                        <label for="" class="form-label">اولویت</label>
                        <select class="form-select" name="priority" id="">
                            <option value="">انتخاب کنید</option>
                            <option value="1">کم</option>
                            <option value="2">متوسط</option>
                            <option value="3">زیاد</option>
                        </select>
                    </div>
                    <div class="col-md-12 mb-1">
                        <label for="" class="form-label">توضیحات</label>
                        <textarea style="  height: 150px;" class="form-control" placeholder="توضیح"
                                  name='description'>  </textarea>


                    </div>
                    <div class="mt-1">
                        <button type="submit" class="btn btn-primary me-2">ثبت</button>
                    </div>

                </div>
            </form>
        </div>
    </div>
    <script>
        let operation = document.getElementById('operationselect')
        let department = document.getElementById('departmentselect')

        function changePartDisplay(char) {
            let is_machine = document.getElementById('is_machine')
            let is_department = document.getElementById('is_department')
            let operation_div = document.getElementById('operation_div')
            let department_div = document.getElementById('department_div')
            let formElement = document.getElementById('formValidationExamples')
            if (is_machine.checked && char === 'd') {
                formElement.reset()
                is_department.checked = true
                department.required = true
                operation.required = false
            }
            if (is_department.checked && char === 'm') {
                formElement.reset()
                is_machine.checked = true
                operation.required = true
                department.required = false

            }

            if (is_machine.checked) {
                document.getElementById('part_div').classList.remove('d-none')
                document.getElementById('stuff_div').classList.add('d-none')
                department_div.classList.add('d-none')
                operation_div.classList.remove('d-none')
            }
            if (is_department.checked) {
                document.getElementById('part_div').classList.add('d-none')
                document.getElementById('stuff_div').classList.remove('d-none')
                department_div.classList.remove('d-none')
                operation_div.classList.add('d-none')
            }

        }


        function getParts() {
            let partSelect = document.getElementById('partselect')
            partSelect.innerHTML = ''

            function addPartOption(item, index) {
                let opt = document.createElement('option');
                opt.value = item[1];
                opt.innerHTML = item[0];
                partSelect.appendChild(opt);
            }


            (async function () {
                await fetch(`/ajax/get-parts/?operation_id=${operation.value}`).then(function (response) {
                    return response.json();
                }).then(function (data) {
                    data.data.forEach(addPartOption);
                });
            })();

        }

        function getStuff() {
            let stuffSelect = document.getElementById('stuffselect')
            stuffSelect.innerHTML = ''


            function addStuffOption(item, index) {
                let opt = document.createElement('option');
                opt.value = item[1];
                opt.innerHTML = item[0];
                stuffSelect.appendChild(opt);
            }

            (async function () {
                await fetch(`/ajax/get-stuff/?department_id=${department.value}`).then(function (response) {
                    return response.json();
                }).then(function (data) {
                    data.data.forEach(addStuffOption);
                });
            })();
        }

    </script>
{% endblock content %}

templates/order/detail.html
{% extends '../base.html' %}

{% load static %}
{% load jalali_tags %}

{% block content %}

    <h4 class="py-3 breadcrumb-wrapper mb-2">مشاهده درخواست</h4>

    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
    {% endfor %}

    <div class="card">
        <div class="card-body">
            <div class="row g-3">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <tr>
                            <td><b> درخواست کننده : </b> {{ order.user.profile }}</td>
                            <td><b> شماره درخواست :</b> {{ order.orderId }}</td>
                            <td><b>تاریخ درخواست :</b>
                                {{ order.createdAt|to_jalali:'%y/%m/%d' }}
                            </td>
                        </tr>
                        <tr>
                            <td><b> واحد :</b> {{ order.departmentName }}</td>
                            <td>زیرگروه :
                                {% for sub in order.subGroup.all %}
                                    {{ sub.name }}
                                {% endfor %}
                            </td>
                            <td><b>عملیات :</b>{{ order.operationName }}</td>
                        </tr>
                        <tr>
                            <td><b>شرح درخواست</b></td>
                            <td colspan="2">{{ order.description|safe }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="table-responsive">
        <h4>لیست کارهای انجام شده</h4>
        {% for task in order.task.all|dictsort:"date" %}
            <table class="table table-bordered text-center mb-4">
                <tr>
                    <td colspan="4"><b> نام مجری :</b> {{ task.user.profile }}</td>
                </tr>
                <tr>
                    <td rowspan="4" {% if task.completed %} class="bg-label-success" {% else %}
                        class="bg-label-danger" {% endif %}>
                        <b> تاریخ : </b> {{ task.date|to_jalali:'%y/%m/%d' }}
                    </td>
                    <td><b>ساعت شروع : </b>
                        <dir
                        ="ltr">{{ task.start_time|time:'h:i A' }}</td>
                    <td><b>ساعت پایان : </b>
                        <dir
                        ="ltr">{{ task.end_time|time:'h:i A' }}</b></td>
                    <td><b>وضعیت : </b> {% if task.completed %}
                        <span class="badge bg-label-success">کامل</span>
                    {% else %}
                        <span class="badge bg-label-danger">ناقص</span>
                    {% endif %}
                    </td>
                </tr>
                <tr>
                    <td><b>شرح فعالیت </b></td>
                    <td colspan="3" style="text-align: justify;">{{ task.description }}</td>
                </tr>
                <tr>
                    <td><b>شرح لوازم مصرفی </b></td>
                    <td colspan="3" style="text-align: justify;">{{ task.description2 }}</td>
                </tr>
            </table>
        {% endfor %}
    </div>
    </div>
    <!--/ View Order Details -->
    </div>
    </div>


{% endblock content %}

templates/order/edit.html
{% extends '../base.html' %}
{% load crispy_forms_filters %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <h4 class="py-3 breadcrumb-wrapper mb-2">ویرایش درخواست</h4>

    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">{{ message }}</div>
        {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endif %}
    {% endfor %}

    <div class="card">
        <div class="card-body">
            <div class="mb-3">
                <div class="alert alert-solid-primary" role="alert">
                    <label for="">وضعیت درخواست : {{ order.get_status_display }}</label>
                    {% if not order.isConfirmed and perms.base.change_order %}
                        <button type="button" class="btn btn-label-primary btn-sm" data-orderid="{{ order.orderId }}"
                                id="confirmOrderBtn">تایید درخواست
                        </button>
                    {% endif %}
                </div>
            </div>
            <form id="formValidationExamples" action="{% url 'order_edit' order.orderId %}" method="post">
                {% csrf_token %}
                <div class="row g-4">
                    <div class="col-md-3 mb-1">
                        <label for="" class="form-label">عملیات درخواستی*</label>
                        <select class="select2 form-select form-select-lg" data-allow-clear="true" name="operation"
                                required>
                            {% for operation in operations %}
                                <option value="{{ operation.id }}" {% if operation.id == order.operation.id %} selected
                                {% endif %}>
                                    {{ operation.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    {% if order.is_for_machine %}
                        <div class="col-md-3 mb-1">
                            <label for="" class="form-label">قطعات مربوطه</label>
                            <select class="select2 form-select form-select-lg" id="partselect" data-allow-clear="true"
                                    name="part">
                                <option value="">لطفا انتخاب کنید</option>
                                {% for part in order.operation.parts.all %}
                                    <option value="{{ part.id }}" {% if order.part.id == part.id %}
                                            selected{% endif %}>{{ part.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    {% elif order.is_for_department %}
                        <div class="col-md-3 mb-1">
                            <label for="" class="form-label">وسیله مربوطه</label>
                            <select class="select2 form-select form-select-lg" id="stuffselect" data-allow-clear="true"
                                    name="part">
                                <option value="">لطفا انتخاب کنید</option>
                                {% for stuff in order.department.stuffs.all %}
                                    <option value="{{ stuff.id }}" {% if order.stuff == stuff.id %}
                                            selected{% endif %}>{{ stuff.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    {% endif %}
                    <div class="col-md-2 mb-1">
                        <label for="" class="form-label">واحد*</label>
                        <select class="select2 form-select form-select-lg" data-allow-clear="true" name="department"
                                required>
                            {% for department in departments %}
                                <option value="{{ department.id }}" {% if department.id == order.department.id %}
                                        selected
                                {% endif %}>{{ department.name }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="col-md-2 mb-1">
                        <label for="second_status" class="form-label">وضعیت</label>
                        <select class="select2 form-select form-select-lg" id="second_status" data-allow-clear="true"
                                name="status"
                                required>
                            {% for key, text in status_choices %}
                                <option value="{{ key }}"
                                        {% if order.status == key %} selected
                                        {% endif %}>{{ text }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-md-2 mb-1">
                        <label for="select2Success" class="form-label">زیرگروه</label>
                        <div class="select2-success">
                            <select id="select2Success" class="select2 form-select" name="subgroup" multiple required>
                                {% for subgroup in subgroups %}
                                    <option value="{{ subgroup.id }}" {% for order_sub in order.subGroup.all %}
                                        {% if order_sub.id == subgroup.id %} selected {% endif %} {% endfor %}>
                                        {{ subgroup.name }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <div class="col-md-2 mb-1">
                        <label for="" class="form-label">اولویت</label>
                        <select class="form-select" name="priority" id="">
                            <option value="">انتخاب کنید</option>
                            <option value="1" {% if order.priority == '1' %} selected {% endif %}>کم</option>
                            <option value="2" {% if order.priority == '2' %} selected {% endif %}>متوسط</option>
                            <option value="3" {% if order.priority == '3' %} selected {% endif %}>زیاد</option>
                        </select>
                    </div>

                    <div class="col-md-12 mb-1">
                        {{ form.description|as_crispy_field }}
                    </div>
                </div>
                <div class="mt-1">
                    <button type="submit" class="btn btn-primary me-2">ویرایش</button>
                </div>
            </form>
        </div>
    </div>


{% endblock content %}